RecyclerView
dinhanhx/flickr pull request #7
Opened 2020-12-27 17:36 UTC by huonglarne

Probably the most up to date code?

2020-12-28 06:53 UTC, dinhanhx requested changes
Delete `ActivityMain1.*`

Delete comments in `fragment_imageragment.xml`

2020-12-30 08:09 UTC, DDHLong approved these changes

2020-12-30 08:26 UTC, dinhanhx approved these changes

2020-12-30 08:28 UTC, dinhanhx commented
LGTM
Please blame Kim Ngan for any break

2020-12-30 08:29 UTC, merged